name: CI

on:
  - push
  - pull_request

jobs:
  build:
    name: eclingo ${{ matrix.os }} - python${{ matrix.python-version }} - clingo ${{ matrix.clingo-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        python-version: ['3.9', '3.11', '3.12']
        clingo-version: ['>=5.5.0,<5.6.0','>=5.6.0,<5.7.0','>=5.7.0,<5.8.0']

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install "clingo${{ matrix.clingo-version }}"
        python -m pip install nox
        python -m pip install isort
    
    - name: Clingo version
      id: clingo-version
      run: |
        echo "CLINGO_VERSION=$(python -c 'import clingo; print(clingo.__version__)')" >> $GITHUB_ENV

    - name: Cache nox
      id: cache-nox
      uses: actions/cache@v3
      with:
        path: .nox
        key: ${{ runner.os }}-python-${{ matrix.python-version }}-clingo-${{ env.CLINGO_VERSION }}-nox

    - name: Info
      run: |
        python -VV
        pip list

    - name: run all tests and static checks
      if: matrix.python-version == '3.12' && matrix.clingo-version == '>=5.7.0,<5.8.0'
      run: nox -r

    - name: run only tests
      if: matrix.python-version != '3.12' || matrix.clingo-version != '>=5.7.0,<5.8.0'
      run: nox -rs all_tests

